# Generated by Django 3.2.3 on 2021-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_evuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
