# Generated by Django 3.2.3 on 2021-05-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
        ('users', '0003_alter_evuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='evuser',
            name='profile_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aws.awsdocument'),
        ),
        migrations.AlterField(
            model_name='evuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
