# Generated by Django 3.2.3 on 2021-05-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('S', 'Scheduled'), ('C', 'Canceled')], max_length=1)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('finish_hour', models.TimeField(blank=True, null=True)),
                ('evs_link', models.URLField(blank=True, null=True)),
                ('event_website', models.URLField(blank=True, null=True)),
                ('tickets_website', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='events.Category')),
                ('event_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aws_document', to='aws.awsdocument')),
                ('interested', models.ManyToManyField(blank=True, related_name='users_interested', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='users_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
