# Generated by Django 3.2.3 on 2021-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsdocument',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
