# Generated by Django 3.2.3 on 2021-06-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='members',
            new_name='notified',
        ),
    ]
