# Generated by Django 3.2.3 on 2021-06-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_rename_members_notification_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationitem',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_item_notification', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_item_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
