name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: evsdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        env:
          SECRET_KEY_EVS: ${{ secrets.SECRET_KEY_EVS }}
          DB_STRING: ${{secrets.DB_STRING}}
        run: tox -e py